### ISSUE TITLE
Refonte du back office pour l'environnement de test

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-freepay-magento#17]
Détails :
--
- Installer la version 1.9
- Ajouter le Template Madison Island: [cliquer ici!](http://magento-demo.lexiconn.com/) 
- Installer les samples 
- Installer les module de paiement suivant:
  - Amazon Pay (https://www.magentocommerce.com/magento-connect/amazon-pay-and-login-with-amazon-for-europe.html) 
   - Paypal One Touch (https://www.magentocommerce.com/magento-connect/paypal-one-touch-and-in-context-checkout.html)
  - Adyen (https://www.magentocommerce.com/magento-connect/adyen-payments-platform.html) 
  - Stripe (https://www.magentocommerce.com/magento-connect/pay-using-stripe.html)
  - Payplug (https://www.magentocommerce.com/magento-connect/payplug-payment-gateway-by-j2t.html)

**Comment by mehdichaouch** [comment]
Me donner la liste des modules souhaités en fournissant les url de MagentoCommerce (e.g. https://www.magentocommerce.com/magento-connect/pay-with-amazon-for-magento-1.html)
